# long list of names to use by the generator
# Pyhton based npc name generator

firstNames = {
    'female': [
        'Jessica',
        'Ashley',
        'Amanda',
        'Brittany',
        'Jennifer',
        'Sarah',
        'Stephanie',
        'Samantha',
        'Elizabeth',
        'Lauren',
        'Nicole',
        'Megan',
        'Heather',
        'Amber',
        'Melissa',
        'Tiffany',
        'Danielle',
        'Emily',
        'Rachel',
        'Christina',
        'Michelle',
        'Kayla',
        'Laura',
        'Kimberly',
        'Rebecca',
        'Courtney',
        'Katherine',
        'Amy',
        'Crystal',
        'Sara',
    ],
    'male': [
        'Michael',
        'Christopher',
        'Matthew',
        'Joshua',
        'David',
        'Andrew',
        'Daniel',
        'Justin',
        'James',
        'Robert',
        'John',
        'Joseph',
        'Ryan',
        'Nicholas',
        'William',
        'Brandon',
        'Anthony',
        'Jonathan',
        'Kevin',
        'Kyle',
        'Eric',
        'Brian',
        'Steven',
        'Thomas',
        'Timothy',
        'Adam',
        'Jacob',
        'Jason',
        'Zachary',
        'Benjamin',
    ]
}

lastNames = {
    'common': [
        'Smith',
        'Johnson',
        'Williams',
        'Brown',
        'Jones',
        'Miller',
        'Davis',
        'Garcia',
        'Rodrigue',
        'Wilson',
        'Martinez',
        'Anderson',
        'Taylor',
        'Thomas',
        'Hernande',
        'Moore',
        'Martin',
        'Jackson',
        'Thompson',
        'White',
        'Lopez',
        'Lee',
        'Gonzalez',
        'Harris',
        'Clark',
        'Lewis',
        'Robinson',
        'Walker',
        'Perez',
        'Hall',
        'Young',
        'Allen',
        'Sanchez',
        'Wright',
        'King',
        'Scott',
        'Green',
        'Baker',
        'Adams',
        'Nelson',
        'Hill',
        'Ramirez',
        'Campbell',
        'Mitchell',
        'Roberts',
        'Carter',
        'Phillips',
        'Evans',
        'Turner',
        'Torres',
        'Parker',
        'Collins',
        'Edwards',
        'Stewart',
        'Flores',
        'Morris',
        'Nguyen',
        'Murphy',
        'Rivera',
        'Cook',
        'Rogers',
        'Morgan',
        'Peterson',
        'Cooper',
        'Reed',
        'Bailey',
        'Bell',
        'Gomez',
        'Kelly',
        'Howard',
        'Ward',
        'Cox',
        'Diaz',
        'Richards',
        'Wood',
        'Watson',
        'Brooks',
        'Bennett',
        'Gray',
        'James',
        'Reyes',
        'Cruz',
        'Hughes',
        'Price',
        'Myers',
        'Long',
        'Foster',
        'Sanders',
        'Ross',
        'Morales',
        'Powell',
        'Sullivan',
        'Russell',
        'Ortiz',
        'Jenkins',
        'Gutierre',
        'Perry',
        'Butler',
        'Barnes',
        'Fisher',
    ],
    'rare': [
        'Afify',
        'Allaband',
        'Amspoker',
        'Ardolf',
        'Atonal',
        'Banasiewicz',
        'Beischel',
        'Bidelspach',
        'Bombardo',
        'Bressett',
        'Bullara',
        'Calascione',
        'Carpiniello',
        'Chaparala',
        'Chorro',
        'Clyborne',
        'Concord',
        'Cripple',
        'Dallarosa',
        'Delatejera',
        'Denetsosie',
        'Dierksheide',
        'Dolivo',
        'Doxon',
        'Duckstein',
        'Ekundayo',
        'Eswaran',
        'Featheringham',
        'Feyrer',
        'Floding',
        'Freling',
        'Gancayco',
        'Gayhardt',
        'Gessele',
        'Ginart',
        'Goscicki',
        'Grigoras',
        'Guillebeaux',
        'Hanschu',
        'Hayda',
        'Henris',
        'Hinsen',
        'Hoig',
        'Hulls',
        'Ionadi',
        'Javernick',
        'Jonguitud',
        'Kasprak',
        'Kentala',
        'Kleinhaus',
        'Konietzko',
        'Kronbach',
        'Kustka',
        'Lahde',
        'Latcha',
        'Leneghan',
        'Llama',
        'Luettgen',
        'Madris',
        'Maloles',
        'Marudas',
        'Mccallops',
        'Melgren',
        'Mickelberg',
        'Mishchuk',
        'Mosheyev',
        'Naese',
        'Nierling',
        'Occhialini',
        'Ollenburger',
        'Owsinski',
        'Panchak',
        'Pegany',
        'Petrunich',
        'Ploense',
        'Protich',
        'Ragsdill',
        'Reat',
        'Riggie',
        'Rugger',
        'Salotto',
        'Scheben',
        'Schoellman',
        'Serranogarcia',
        'Shuldberg',
        'Skalbeck',
        'Snearl',
        'Spedoske',
        'Stawarski',
        'Stolly',
        'Suco',
        'Tahhan',
        'Tartal',
        'Throndsen',
        'Torsney',
        'Tuffin',
        'Usoro',
        'Vanidestine',
        'Viglianco',
        'Vozenilek',
    ]
}

jobTitles = [
    'Administrative assistant',
    'Administrative coordinator',
    'Secretary',
    'Receptionist',
    'Administrative manager',
    'Administrative director',
    'Administrative specialist',
    'Executive assistant',
    'Support assistant',
    'Program coordinator',
    'Client relations manager',
    'Mail clerk',
    'Office manager',
    'Bill collector',
    'Risk manager',
    'Program manager',
    'File clerk',
    'Program administrator',
    'Administrative officer',
    'Staff assistant',
    'Business development coordinator',
    'Business reporter',
    'Actuary',
    'Account manager',
    'Product manager',
    'Content manager',
    'Account specialist',
    'Client advisor',
    'Team lead',
    'Analyst',
    'Customer service associate',
    'Technical support specialist',
    'Help desk coordinator',
    'Account representative',
    'Call center customer support',
    'Customer service agent',
    'Bilingual customer service representative',
    'Customer relationship coordinator',
    'Customer service manager',
    'Customer service officer',
    'Benefits administrator',
    'Accountant',
    'Auditor',
    'Budget analyst',
    'Bookkeeper',
    'Controller',
    'Payroll manager',
    'Financial planner',
    'Accounts payable clerk',
    'Accounts receivable clerk',
    'Accounting director',
    'Investment banking analyst',
    'Financial analyst',
    'Junior tax associate',
    'Credit analyst',
    'Information security analyst',
    'Computer programmer',
    'Technical specialist',
    'Web developer',
    'Mobile application developer',
    'Cloud architect',
    'IT coordinator',
    'Computer systems manager',
    'Network engineer',
    'Telecommunications specialist',
    'IT director',
    'Technical operations officer',
    'Java developer',
    'Software architect',
    'Computer research scientist',
    'Head of operations',
    'Team leader',
    'Officer',
    'Supervisor',
    'Manager',
    'Executive',
    'President',
    'Principal',
    'Assistant manager',
    'Administrator',
    'General counsel',
    'Arbitrator',
    'Case manager',
    'Legal analyst',
    'Mediator',
    'Legal assistant',
    'Legal aide',
    'Legal consultant',
    'Corporate attorney',
    'Legal secretary',
    'Brand manager',
    'Social media manager',
    'SEO specialist',
    'Creative director',
    'Marketing coordinator',
    'Marketing assistant',
    'Digital content specialist',
    'Marketing promotions specialist',
    'Digital marketing coordinator',
    'E-commerce marketing manager',
    'Advertising director',
    'Copywriter',
    'Media buyer',
    'Media planner',
    'Marketing content assistant',
    'Public information specialist',
    'Public relations manager',
    'Publicist',
    'Communications coordinator',
    'Internal communications specialist',
    'Media relations manager',
    'External communications director',
    'Media relations assistant',
    'Public affairs coordinator',
    'Strategic communications director',
    'Purchasing manager',
    'Materials manager',
    'Procurement director',
    'Purchasing agent',
    'Procurement clerk',
    'Logistics team leader',
    'Production planner',
    'Sourcing officer',
    'Logistics supervisor',
    'Purchasing associate',
    'Supply chain supervisor',
    'Sales representative',
    'B2B sales coordinator',
    'National account sales coordinator',
    'Sales manager',
    'Regional sales director',
    'Market development manager',
    'Inside sales associate',
    'Account executive',
    'Sales trainee',
    'Financial sales assistant',
]
